//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cluster_Details
    {
        public int Clt_Dtl_Id { get; set; }
        public Nullable<int> Clt_Id { get; set; }
        public Nullable<int> DeepBorewellRegdId { get; set; }
    }
}
