//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Registration_Detail
    {
        public int DeepBorewellRegdId { get; set; }
        public string RegNo { get; set; }
        public string FarmerName { get; set; }
        public string DistrictName { get; set; }
        public string Block_Ulb_Name { get; set; }
        public Nullable<int> Clt_Id { get; set; }
        public string Clt_No { get; set; }
    }
}
