//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeepBorewell_PattaDetails
    {
        public int PattaId { get; set; }
        public Nullable<int> DeepBorewellRegdId { get; set; }
        public string Pro_PlotNo { get; set; }
        public string Pro_KhataNo { get; set; }
        public string Pro_LandArea { get; set; }
        public string LandPattaFile { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModOn { get; set; }
        public Nullable<int> ModBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
