//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demo_Table_Rajesh
    {
        public int Id { get; set; }
        public string Service_Code { get; set; }
        public string Description_of_work { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Rate_per_Unit { get; set; }
        public string Application_Number { get; set; }
        public string Length { get; set; }
        public string Breadth { get; set; }
        public string Height { get; set; }
        public string Content_Area { get; set; }
        public string Quantity { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
