//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EE_Verify
    {
        public int EE_Verifyappid { get; set; }
        public Nullable<int> District { get; set; }
        public Nullable<int> block { get; set; }
        public Nullable<int> panchayat { get; set; }
        public Nullable<System.DateTime> Fdate { get; set; }
        public Nullable<System.DateTime> Tdate { get; set; }
        public Nullable<int> AssignTo { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Addon { get; set; }
        public string Addby { get; set; }
        public Nullable<System.DateTime> ModOn { get; set; }
        public string Modby { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
    }
}
