//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hcm_Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hcm_Property()
        {
            this.Hcm_Property_House = new HashSet<Hcm_Property_House>();
            this.Hcm_Property_ImmovableProperties = new HashSet<Hcm_Property_ImmovableProperties>();
            this.Hcm_Property_Land = new HashSet<Hcm_Property_Land>();
            this.Hcm_Property_MovableProperty = new HashSet<Hcm_Property_MovableProperty>();
            this.Hcm_Property_OtherMovable = new HashSet<Hcm_Property_OtherMovable>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hcm_Property_House> Hcm_Property_House { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hcm_Property_ImmovableProperties> Hcm_Property_ImmovableProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hcm_Property_Land> Hcm_Property_Land { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hcm_Property_MovableProperty> Hcm_Property_MovableProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hcm_Property_OtherMovable> Hcm_Property_OtherMovable { get; set; }
    }
}
