//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_EmployeeDtl
    {
        public int Employee_Id { get; set; }
        public string Employee_Code { get; set; }
        public string Employee_Name { get; set; }
        public string Email_Id { get; set; }
        public string Mobile_No { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public string Emp_Class { get; set; }
        public string Gender { get; set; }
        public string Bank_Name { get; set; }
        public string Ac_No { get; set; }
        public string IFSC { get; set; }
        public string UAN { get; set; }
        public string PAN { get; set; }
        public string GIS_No { get; set; }
        public string Bill_No { get; set; }
        public string PF_No { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string Area { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Approval1 { get; set; }
        public Nullable<int> Approval2 { get; set; }
        public Nullable<int> Approval3 { get; set; }
        public Nullable<int> Approval4 { get; set; }
        public Nullable<int> Approval5 { get; set; }
    }
}
