//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OLICEntities : DbContext
    {
        public OLICEntities()
            : base("name=OLICEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankUpdatePayment> BankUpdatePayments { get; set; }
        public virtual DbSet<DeepBorewell_PattaDetails> DeepBorewell_PattaDetails { get; set; }
        public virtual DbSet<EE_Verify> EE_Verify { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<FileType> FileTypes { get; set; }
        public virtual DbSet<LCMS_AssignedLawer> LCMS_AssignedLawer { get; set; }
        public virtual DbSet<LCMS_Case_Hearing_Doc> LCMS_Case_Hearing_Doc { get; set; }
        public virtual DbSet<LCMS_Case_Hearing_Dtls> LCMS_Case_Hearing_Dtls { get; set; }
        public virtual DbSet<LCMS_CaseDetails> LCMS_CaseDetails { get; set; }
        public virtual DbSet<LCMS_CaseDoc> LCMS_CaseDoc { get; set; }
        public virtual DbSet<LCMS_Mst_CaseType> LCMS_Mst_CaseType { get; set; }
        public virtual DbSet<LCMS_Mst_Compliance_Time> LCMS_Mst_Compliance_Time { get; set; }
        public virtual DbSet<LCMS_Mst_Court> LCMS_Mst_Court { get; set; }
        public virtual DbSet<LCMS_Status> LCMS_Status { get; set; }
        public virtual DbSet<LCMS_UserLog> LCMS_UserLog { get; set; }
        public virtual DbSet<ManageUser> ManageUsers { get; set; }
        public virtual DbSet<OLIC_Block_Ulb> OLIC_Block_Ulb { get; set; }
        public virtual DbSet<OLIC_District_Mst> OLIC_District_Mst { get; set; }
        public virtual DbSet<OLIC_Gram_Panchayat> OLIC_Gram_Panchayat { get; set; }
        public virtual DbSet<OLIC_Test> OLIC_Test { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<Vw_DeepBorewellRegdDtl> Vw_DeepBorewellRegdDtl { get; set; }
        public virtual DbSet<vw_input_case_list> vw_input_case_list { get; set; }
        public virtual DbSet<DeepBorewell_Registration> DeepBorewell_Registration { get; set; }
        public virtual DbSet<DBW_Mst_DPR> DBW_Mst_DPR { get; set; }
        public virtual DbSet<Mst_OlicDtl> Mst_OlicDtl { get; set; }
        public virtual DbSet<Mst_Circle> Mst_Circle { get; set; }
        public virtual DbSet<Mst_Division> Mst_Division { get; set; }
        public virtual DbSet<Mst_Section> Mst_Section { get; set; }
        public virtual DbSet<Mst_SubDivision> Mst_SubDivision { get; set; }
        public virtual DbSet<Scrap_Catrgory_Mst> Scrap_Catrgory_Mst { get; set; }
        public virtual DbSet<Scrap_code> Scrap_code { get; set; }
        public virtual DbSet<Scrap_Details_Entry> Scrap_Details_Entry { get; set; }
        public virtual DbSet<Scrap_Item_Mst> Scrap_Item_Mst { get; set; }
        public virtual DbSet<FinacialYear> FinacialYears { get; set; }
        public virtual DbSet<Hcm_ApplyLeave> Hcm_ApplyLeave { get; set; }
        public virtual DbSet<HCM_EmployeeDtl> HCM_EmployeeDtl { get; set; }
        public virtual DbSet<HCM_LeaveBalance> HCM_LeaveBalance { get; set; }
        public virtual DbSet<HCM_LeaveMaster> HCM_LeaveMaster { get; set; }
        public virtual DbSet<Hcm_Property> Hcm_Property { get; set; }
        public virtual DbSet<vwEmployeesByLeaveType> vwEmployeesByLeaveTypes { get; set; }
        public virtual DbSet<Hcm_Property_House> Hcm_Property_House { get; set; }
        public virtual DbSet<Hcm_Property_ImmovableProperties> Hcm_Property_ImmovableProperties { get; set; }
        public virtual DbSet<Hcm_Property_Land> Hcm_Property_Land { get; set; }
        public virtual DbSet<Hcm_Property_MovableProperty> Hcm_Property_MovableProperty { get; set; }
        public virtual DbSet<Hcm_Property_OtherMovable> Hcm_Property_OtherMovable { get; set; }
        public virtual DbSet<Cluster> Clusters { get; set; }
        public virtual DbSet<Cluster_Details> Cluster_Details { get; set; }
        public virtual DbSet<DB_Registration_Detail> DB_Registration_Detail { get; set; }
        public virtual DbSet<Demo_Table_Rajesh> Demo_Table_Rajesh { get; set; }
        public virtual DbSet<Vw_DprEstimation> Vw_DprEstimation { get; set; }
    
        public virtual ObjectResult<sp_case_hearing_detail_Result> sp_case_hearing_detail(Nullable<int> caseid, Nullable<int> userid)
        {
            var caseidParameter = caseid.HasValue ?
                new ObjectParameter("caseid", caseid) :
                new ObjectParameter("caseid", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_case_hearing_detail_Result>("sp_case_hearing_detail", caseidParameter, useridParameter);
        }
    
        public virtual ObjectResult<sp_case_hearing_doc_detail_Result> sp_case_hearing_doc_detail(Nullable<int> hearingid, string url)
        {
            var hearingidParameter = hearingid.HasValue ?
                new ObjectParameter("hearingid", hearingid) :
                new ObjectParameter("hearingid", typeof(int));
    
            var urlParameter = url != null ?
                new ObjectParameter("url", url) :
                new ObjectParameter("url", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_case_hearing_doc_detail_Result>("sp_case_hearing_doc_detail", hearingidParameter, urlParameter);
        }
    
        public virtual ObjectResult<sp_input_case_doc_detail_Result> sp_input_case_doc_detail(Nullable<int> caseid, string url)
        {
            var caseidParameter = caseid.HasValue ?
                new ObjectParameter("caseid", caseid) :
                new ObjectParameter("caseid", typeof(int));
    
            var urlParameter = url != null ?
                new ObjectParameter("url", url) :
                new ObjectParameter("url", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_input_case_doc_detail_Result>("sp_input_case_doc_detail", caseidParameter, urlParameter);
        }
    
        public virtual ObjectResult<sp_lcms_user_log_Result> sp_lcms_user_log(Nullable<int> caseid)
        {
            var caseidParameter = caseid.HasValue ?
                new ObjectParameter("caseid", caseid) :
                new ObjectParameter("caseid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_lcms_user_log_Result>("sp_lcms_user_log", caseidParameter);
        }
    
        public virtual ObjectResult<sp_deepBorewell_REgdeatils_Result> sp_deepBorewell_REgdeatils(Nullable<int> deepBorewellRegdId)
        {
            var deepBorewellRegdIdParameter = deepBorewellRegdId.HasValue ?
                new ObjectParameter("DeepBorewellRegdId", deepBorewellRegdId) :
                new ObjectParameter("DeepBorewellRegdId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_deepBorewell_REgdeatils_Result>("sp_deepBorewell_REgdeatils", deepBorewellRegdIdParameter);
        }
    
        public virtual ObjectResult<sp_DeepBorewell_PattaDetails_Result> sp_DeepBorewell_PattaDetails(Nullable<int> deepBorewellRegdId, string url)
        {
            var deepBorewellRegdIdParameter = deepBorewellRegdId.HasValue ?
                new ObjectParameter("DeepBorewellRegdId", deepBorewellRegdId) :
                new ObjectParameter("DeepBorewellRegdId", typeof(int));
    
            var urlParameter = url != null ?
                new ObjectParameter("url", url) :
                new ObjectParameter("url", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DeepBorewell_PattaDetails_Result>("sp_DeepBorewell_PattaDetails", deepBorewellRegdIdParameter, urlParameter);
        }
    
        public virtual ObjectResult<sp_input_case_detail_Result> sp_input_case_detail(Nullable<int> caseid)
        {
            var caseidParameter = caseid.HasValue ?
                new ObjectParameter("caseid", caseid) :
                new ObjectParameter("caseid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_input_case_detail_Result>("sp_input_case_detail", caseidParameter);
        }
    
        public virtual ObjectResult<sp_scrap_detail_category_Result> sp_scrap_detail_category(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_scrap_detail_category_Result>("sp_scrap_detail_category", idParameter);
        }
    
        public virtual ObjectResult<sp_scrap_item_detail_category_wise_Result> sp_scrap_item_detail_category_wise(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_scrap_item_detail_category_wise_Result>("sp_scrap_item_detail_category_wise", idParameter);
        }
    }
}
