//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Circle
    {
        public string CircleId { get; set; }
        public string CircleName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool IsDelete { get; set; }
    }
}
