//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_OlicDtl
    {
        public int OlicMstId { get; set; }
        public string CircleId { get; set; }
        public string CircleName { get; set; }
        public string DivisionId { get; set; }
        public string DivisionName { get; set; }
        public string SubDivisionId { get; set; }
        public string SubDivisionName { get; set; }
        public string SectionId { get; set; }
        public string SectionName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
