//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scrap_Catrgory_Mst
    {
        public int Scrap_Category_Id { get; set; }
        public string MaterialType { get; set; }
        public string Category_Name { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_on { get; set; }
    }
}
