//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_DeepBorewellRegdDtl
    {
        public int DeepBorewellRegdId { get; set; }
        public string DbRegistrationNo { get; set; }
        public string FarmerName { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Category { get; set; }
        public string AadhaarNo { get; set; }
        public string BPLCardNo { get; set; }
        public string Ad_Village { get; set; }
        public Nullable<int> Ad_DistrictId { get; set; }
        public Nullable<int> Ad_BlockId { get; set; }
        public Nullable<int> Ad_GramPanchayatId { get; set; }
        public string Ad_PostOffice { get; set; }
        public string Pro_Village { get; set; }
        public Nullable<int> Pro_DistrictId { get; set; }
        public Nullable<int> Pro_BlockId { get; set; }
        public Nullable<int> Pro_GramPanchayatId { get; set; }
        public string Pro_PostOffice { get; set; }
        public string AadharFileDtl { get; set; }
        public string BplFileDtl { get; set; }
        public string DistrictName { get; set; }
        public string Block_Ulb_Name { get; set; }
        public string GRAM_PANCHAYAT_Name { get; set; }
        public Nullable<bool> Is_Bank { get; set; }
        public string Ad_PinCode { get; set; }
        public string Pro_PinCode { get; set; }
        public string FarmerPhotoDtl { get; set; }
        public string AffidavitFileDtl { get; set; }
    }
}
