//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_input_case_list
    {
        public int CaseId { get; set; }
        public string CaseNo { get; set; }
        public string PartyName { get; set; }
        public string CourtName { get; set; }
        public Nullable<int> CourtId { get; set; }
        public string CaseFileDate { get; set; }
        public Nullable<int> CaseTypeId { get; set; }
        public string CaseSubject { get; set; }
        public string CourtOrder { get; set; }
        public string Status { get; set; }
        public string ComplianceTime { get; set; }
        public string LCMS_Status_Name { get; set; }
        public string CaseTypeName { get; set; }
        public Nullable<int> Compliance_Time { get; set; }
        public string PendingAt { get; set; }
        public string appstatus { get; set; }
        public Nullable<int> CDays { get; set; }
        public string AssignedDate { get; set; }
        public Nullable<int> Assign_Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string LawerName { get; set; }
    }
}
