//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmployeesByLeaveType
    {
        public int Leave_Id { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Count { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
        public string remarks3 { get; set; }
        public string Remarks4 { get; set; }
        public string Remarks5 { get; set; }
        public Nullable<bool> Status1 { get; set; }
        public Nullable<bool> Status2 { get; set; }
        public Nullable<bool> Status3 { get; set; }
        public Nullable<bool> Status4 { get; set; }
        public Nullable<bool> Status5 { get; set; }
        public Nullable<int> Approval1 { get; set; }
        public Nullable<int> Approval2 { get; set; }
        public Nullable<int> Approval3 { get; set; }
        public Nullable<int> Approval4 { get; set; }
        public Nullable<int> Approval5 { get; set; }
        public string PendingAt { get; set; }
        public Nullable<int> Leave_Typeid { get; set; }
        public string Approverejct { get; set; }
        public Nullable<int> Addby { get; set; }
        public Nullable<System.DateTime> Addon { get; set; }
        public Nullable<int> Modby { get; set; }
        public Nullable<System.DateTime> Modon { get; set; }
        public string Employee_Name { get; set; }
        public string LeaveType { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
        public string Designation { get; set; }
    }
}
